@echo off
echo Installing dependencies...
call npm install

echo Pushing database schema...
call npx prisma db push

echo Seeding database...
node prisma/seed.js

echo Starting development server...
call npm run dev
